# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 19:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='posttype',
            new_name='ptype',
        ),
    ]
