# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170804_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank='true', upload_to='launchingl/'),
        ),
    ]
